### ISSUE TITLE
Can not use Terraform version 0.12 

### ISSUE THREAD

**Issue by lionelg3** [remijouannet/terraform-provider-osc#5]
Hy,

I wanted to try the new "for expressions" of Terraform. According to the changelog the osc plugin must be rebuild with version "0.12".

```
terraform plan

Error: Failed to instantiate provider "osc" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

[https://github.com/hashicorp/terraform/blob/v0.12.0/CHANGELOG.md](https://github.com/hashicorp/terraform/blob/v0.12.0/CHANGELOG.md)
> The wire protocol for provider and provisioner plugins has changed, so plugins built against prior versions of Terraform are not compatible with Terraform v0.12. The most commonly-downloaded providers already had v0.12-compatible releases at the time of v0.12.0 release, but some other providers (particularly those distributed independently of the terraform init installation mechanism) will need to make new releases before they can be used with Terraform v0.12 or later.

**Comment by remijouannet** [comment]
Hi, i will take a look at it if i find the time

**Comment by remijouannet** [comment]
done in v0.8.0
